name: Build and push

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU (для эмуляции ARM)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image (amd64 + arm64)
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/wb-vue-dashboard:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/wb-vue-dashboard:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/wb-vue-dashboard:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/wb-vue-dashboard:buildcache,mode=max
